package views;
import javax.swing.*;
import org.fieb.Batedeira;
import org.fieb.FerroDePassar;
import org.fieb.Liquidificador;
import org.fieb.Tampa;
/**
 *
 * @author Eduardo C.
 */
public class FrmLiquidificador extends javax.swing.JFrame {
    Liquidificador novoLiquidificador = null;
    Liquidificador liquidificadorCadastrado;
    int xMouse;
    int yMouse;
    int level;
    /**
     * Creates new form FrmBatedeira
     */
    public FrmLiquidificador(int level) {
       // lblCalc.setText("<html><body>with<br>linebreak</body></html>");
        initComponents();
        this.level = level;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnDesconto = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JLabel();
        lblDesconto = new javax.swing.JLabel();
        lblCalc = new javax.swing.JLabel();
        btnCalc = new javax.swing.JLabel();
        lblCadastrar1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(959, 496));
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(45, 45, 45));

        jPanel1.setBackground(new java.awt.Color(25, 25, 25));
        jPanel1.setPreferredSize(new java.awt.Dimension(870, 30));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Delete_26px.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Minimize_Window_26px.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(7, 7, 7))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(154, 209, 203));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("LIQUIDIFICADOR");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Back_26px.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(305, 305, 305)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnDesconto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/percentgreen.png"))); // NOI18N
        btnDesconto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDesconto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDescontoMouseClicked(evt);
            }
        });

        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plusgreen.png"))); // NOI18N
        btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseClicked(evt);
            }
        });

        lblDesconto.setBackground(new java.awt.Color(204, 204, 204));
        lblDesconto.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblDesconto.setForeground(new java.awt.Color(204, 204, 204));
        lblDesconto.setText("CALCULAR DESCONTO");
        lblDesconto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblCalc.setBackground(new java.awt.Color(204, 204, 204));
        lblCalc.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblCalc.setForeground(new java.awt.Color(204, 204, 204));
        lblCalc.setText("CALCULAR LB/S");
        lblCalc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnCalc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mediagreen.png"))); // NOI18N
        btnCalc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalcMouseClicked(evt);
            }
        });

        lblCadastrar1.setBackground(new java.awt.Color(204, 204, 204));
        lblCadastrar1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblCadastrar1.setForeground(new java.awt.Color(204, 204, 204));
        lblCadastrar1.setText("CADASTRAR");
        lblCadastrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCadastrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadastrar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnCadastrar)
                        .addGap(151, 151, 151)
                        .addComponent(btnDesconto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalc)
                        .addGap(5, 5, 5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(lblCadastrar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addComponent(lblDesconto)
                        .addGap(97, 97, 97)
                        .addComponent(lblCalc)))
                .addGap(51, 51, 51))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnCadastrar)
                    .addComponent(btnDesconto)
                    .addComponent(btnCalc))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCalc)
                    .addComponent(lblDesconto)
                    .addComponent(lblCadastrar1))
                .addGap(42, 107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        frmPrincipal telaPrincipal = new frmPrincipal(level);
        telaPrincipal.pack();
        telaPrincipal.setLocationRelativeTo(null);
        this.setVisible(false);
        telaPrincipal.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseClicked
        if (this.level == 1) {
            JTextField marca = new JTextField();
            JTextField volt = new JTextField();
            JTextField qnt = new JTextField();
            JTextField cap = new JTextField();
            JTextField preco = new JTextField();
            Object[] message = {
                "Marca:", marca,
                "Voltagem:", volt,
                "Quantidade(L):",qnt,
                "Capacidade(L/s):",cap,
                "Preço(Opcional):",preco
            };

            int option = JOptionPane.showConfirmDialog(null, message, "CADASTRO - LIQUIDIFICADOR", JOptionPane.OK_CANCEL_OPTION);
            if (option == JOptionPane.OK_OPTION) {
                if ((marca.getText().isEmpty() || volt.getText().isEmpty() || qnt.getText().isEmpty() || cap.getText().isEmpty())) {
                    JOptionPane.showMessageDialog(null, "Todos os campos obrigatórios devem ser preenchidos.");
                    return;
                }else{
                    novoLiquidificador = new Liquidificador(marca.getText());
                    novoLiquidificador.setCapacidade(Double.parseDouble(cap.getText()));
                    novoLiquidificador.setQuantidade(Double.parseDouble(qnt.getText()));
                    try {
                        Tampa tampa;
                        do{
                            tampa = new Tampa();                            
                            tampa.setCor(JOptionPane.showInputDialog("Insira a cor da tampa."));
                            tampa.setDescricao(JOptionPane.showInputDialog("Insira a descrição da tampa."));
                            novoLiquidificador.setTampa(tampa);
                            if (tampa.getCor().isEmpty() || tampa.getDescricao().isEmpty()) {
                                JOptionPane.showMessageDialog(null, "Os campos são obrigatórios!");
                            }
                        }while (tampa.getCor().isEmpty() || tampa.getDescricao().isEmpty());
                    if (!(preco.getText().isEmpty())) {
                        novoLiquidificador.setPreco(Double.parseDouble(preco.getText()));
                    }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "O processo de cadastro foi cancelado com sucesso", "Operação cancelada", 2);
                        return;
                    }
                    if (!(novoLiquidificador.setVoltagem(Double.parseDouble(volt.getText())))) {
                        JOptionPane.showMessageDialog(null, "Valor de voltagem invalida, tente novamente", "Operação cancelada", 2);
                        return;
                    }
                        liquidificadorCadastrado = novoLiquidificador;
                }
            } else {
                JOptionPane.showMessageDialog(null, "O processo de cadastro foi cancelado com sucesso", "Operação cancelada", 2);
                return;
            }
            
        } else {
            JTextField marca = new JTextField();
            JTextField preco = new JTextField();
            JTextField volt = new JTextField();
            JTextField qnt = new JTextField();
            JTextField cap = new JTextField();
            Object[] message = {
                "Marca:", marca,
                "Preço:", preco,
                "Voltagem:", volt,
                "Quantidade(L):",qnt,
                "Capacidade(L/s):",cap
            };

            int option = JOptionPane.showConfirmDialog(null, message, "CADASTRO - LIQUIDIFICADOR", JOptionPane.OK_CANCEL_OPTION);
            if (option == JOptionPane.OK_OPTION) {
                if ((marca.getText().isEmpty() || volt.getText().isEmpty() || qnt.getText().isEmpty() || cap.getText().isEmpty() || preco.getText().isEmpty())) {
                    JOptionPane.showMessageDialog(null, "Todos os campos obrigatórios devem ser preenchidos.");
                    return;
                }else{
                    novoLiquidificador = new Liquidificador(Double.parseDouble(preco.getText()),marca.getText());
                    novoLiquidificador.setCapacidade(Double.parseDouble(cap.getText()));
                    novoLiquidificador.setQuantidade(Double.parseDouble(qnt.getText()));
                    if (!(novoLiquidificador.setVoltagem(Double.parseDouble(volt.getText())))) {
                        JOptionPane.showMessageDialog(null, "Valor de voltagem invalida, tente novamente", "Operação cancelada", 2);
                        return;
                    }
                }
                liquidificadorCadastrado = novoLiquidificador;
            }else {
                JOptionPane.showMessageDialog(null, "O processo de cadastro foi cancelado com sucesso", "Operação cancelada", 2);
                return;
            }
        }
        
    }//GEN-LAST:event_btnCadastrarMouseClicked

    private void btnDescontoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDescontoMouseClicked
        try {
            if (liquidificadorCadastrado == null) {
                JOptionPane.showMessageDialog(null, "Você deve cadastrar um liquidificador primeiro.", "Operação cancelada", 2);
            }
            else if(liquidificadorCadastrado.getPreco() == 0){
                    JOptionPane.showMessageDialog(null, "Esse produto é de uso interno e não possui valor de venda.");
            }else{
                String mes = JOptionPane.showInputDialog(null, "Insira o mês corrente", "CALCULANDO DESCONTO", 3);
                double desconto = liquidificadorCadastrado.calculoDesconto(mes);
                if (desconto != 1 && liquidificadorCadastrado.getPreco() !=0) {
                    JOptionPane.showMessageDialog(null, "O desconto a ser aplicado no valor desse produto é "+desconto+" totalizando um preço de R$ "+(liquidificadorCadastrado.getPreco()-liquidificadorCadastrado.calculoDesconto(mes)));
                }
                else{
                    JOptionPane.showMessageDialog(null, "Sem promoções neste produto no mês corrente", "Desconto calculado.", 2);
                }
            }
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_btnDescontoMouseClicked

    private void btnCalcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcMouseClicked
        try {
            JOptionPane.showMessageDialog(null, "A média de litros batidos por segundo desse liquidificador é " + liquidificadorCadastrado.calculaLitrosPorSegundo());
        } catch (Exception ex) {
                if (liquidificadorCadastrado == null) {
                    JOptionPane.showMessageDialog(null, "Você deve cadastrar um liquidificador primeiro.", "Operação cancelada", 2);
                }
        }
    }//GEN-LAST:event_btnCalcMouseClicked

    private void lblCadastrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastrar1MouseClicked
        btnCadastrarMouseClicked(evt);
    }//GEN-LAST:event_lblCadastrar1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBatedeira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBatedeira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBatedeira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBatedeira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCadastrar;
    private javax.swing.JLabel btnCalc;
    private javax.swing.JLabel btnDesconto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCadastrar1;
    private javax.swing.JLabel lblCalc;
    private javax.swing.JLabel lblDesconto;
    // End of variables declaration//GEN-END:variables
}
